// Eye-level stations are inside the architectural room envelopes. Furniture is proposed staging.
export const interiorRooms=[
 {id:'living',label:'Waterfront living',level:'main',position:[22.1,72.3],target:[28.1,80.5],eye:1.62,focus:1.08,fov:68,description:'Sculpted seating, layered textiles and a low stone table, framed by the waterfront glazing.',bounds:[19.7,34.6,72.2,87.3]},
 {id:'dining',label:'Dining room',level:'main',position:[22.3,57.2],target:[28.3,65.8],eye:1.65,focus:1.15,fov:70,description:'An eight-seat dining setting, a statement pendant and warm joinery beside the water-facing living area.',bounds:[19.7,35.7,56.5,72.1]},
 {id:'kitchen',label:'Kitchen',level:'main',position:[9.1,53.6],target:[2.4,43.5],eye:1.58,focus:1.15,fov:74,description:'Light cabinetry, pale stone counters and island, and travertine floors follow the client’s finish direction. Integrated appliances and layered task lighting complete the space.',bounds:[-1.6,10,39,55]},
 {id:'stairs',label:'Stair hall',level:'main',position:[12.5,53.6],target:[16.85,43.6],eye:1.62,focus:1.45,fov:76,description:'Wider wood treads, frameless glass guards with discreet mounting at floor level, and travertine flooring follow the client’s direction. The wider tread dimensions remain a visual approximation.',bounds:[11.4,14.2,33,56]},
 {id:'family',label:'Family lounge',level:'main',position:[7.5,60],target:[3.8,65.8],eye:1.6,focus:1.05,fov:72,description:'A more intimate lounge with soft upholstery and a direct view through the terrace glazing.',bounds:[-.6,9.6,59.8,71.4]},
 {id:'primary',label:'Primary bedroom',level:'upper',position:[22.3,62.3],target:[32,68],eye:1.61,focus:1.15,fov:68,description:'An upholstered bed, layered linens, bedside lighting and a calm material palette opening onto the private terrace.',bounds:[19.8,35.4,59.8,75.4]},
 {id:'bath',label:'Primary bathroom',level:'upper',position:[5.6,58.9],target:[2.5,68.1],eye:1.59,focus:.99,fov:72,description:'Pale stone, fluted timber vanities and charcoal basins follow the photographed finish direction, with a staged freestanding bath.',bounds:[-.5,9.4,57.5,71.3]},
 {id:'closet',label:'Dressing room',level:'upper',position:[4.2,50.45],target:[2.4,42],eye:1.61,focus:1.18,fov:69,description:'Full-height joinery, open shelving, hanging garments and warm integrated lighting.',bounds:[-1.5,9.5,39,55.5]},
 {id:'guest',label:'Guest bedroom',level:'main',position:[22.6,2.4],target:[18.25,9.3],eye:1.57,focus:1.05,fov:70,description:'A finished guest suite with upholstered bedding, bedside lighting and considered storage.',bounds:[11.3,23.7,1,13.5]},
];
