// Curated South Florida PRECONSTRUCTION / new-development buildings.
// Building-level projects (whole towers selling off-plan) — NOT individual MLS
// units. Source of truth: The Poler Team's own vetted new-development research.
// Add a building = append an object here (keep the same shape); the
// /api/preconstructions endpoint + the /preconstruction page + the MCP tools
// all read this one array.
//
// FIELDS: id, name, address, area, city, tagline (optional), developer,
// architecture, interiors, stories, totalUnits, bedrooms (array of ints
// available), sqftMin/Max, pricingFrom (human string per BR), priceFrom
// (number, lowest entry price), pricePerSqft (approx), deliveryYear (earliest
// int), deliveryLabel (human), deposit (structure string), amenities[],
// parkingSpaces (string), description (2-sentence blurb), views,
// constructionStatus, waterfront (bool), shortTermRental (bool), badge,
// photos[] (validated image URLs — HTTP 200 + image/* at build time).

export const PRECONSTRUCTIONS = [
  {
    id: 'cipriani-residences-miami',
    name: 'Cipriani Residences Miami',
    address: '1420 South Miami Avenue',
    area: 'Brickell',
    city: 'Miami',
    tagline: '',
    developer: 'Mast Capital',
    architecture: 'Arquitectonica',
    interiors: '1508 London',
    stories: 80,
    totalUnits: 397,
    bedrooms: [1, 2, 3, 4],
    sqftMin: 1065,
    sqftMax: 3495,
    pricingFrom: '1BR-4BR from $1.7M',
    priceFrom: 1700000,
    pricePerSqft: 1575,
    deliveryYear: 2027,
    deliveryLabel: '2027',
    deposit: '20% at contract, 10% six months after contract, 10% twelve months after contract, 60% at closing (2027)',
    amenities: [
      'Two swimming pools on elevated resort deck',
      'Landscaped sun terrace',
      'Private Cipriani dining rooms',
      'Holistic spa with sauna and treatment rooms',
      'Fitness center',
      'Golf simulator',
      'Pickleball court',
      '24-hour valet',
    ],
    parkingSpaces: '1,650 total parking spaces; 24-hour complimentary valet plus optional self-parking in assigned spaces',
    description: 'Mast Capital\'s Cipriani Residences is Arquitectonica\'s curved, 80-story tower on the Miami River in Brickell, the tallest residential building south of New York and more than 75% sold. Interiors by 1508 London bring genuine Cipriani hospitality service to full-floor and penthouse residences with sweeping bay, river, and skyline views. It is the first Cipriani-branded residential tower in the world.',
    views: 'Biscayne Bay, Miami River, and Downtown Miami skyline',
    waterfront: true,
    shortTermRental: false,
    constructionStatus: 'Under construction — 80-story superstructure nearing topping-off, 2026',
    badge: 'EARLIEST DELIVERY',
    photos: [
      'https://images.prismic.io/cipriani/aVwBzXNYClf9oy_7_EXT04_Crown_B6_New.jpg?auto=format,compress',
    ],
  },
  {
    id: 'baccarat-residences-miami',
    name: 'Baccarat Residences Miami',
    address: '444 Brickell Avenue',
    area: 'Brickell',
    city: 'Miami',
    tagline: '',
    developer: 'Related Group & GTIS Partners',
    architecture: 'Arquitectonica',
    interiors: 'Meyer Davis',
    stories: 75,
    totalUnits: 360,
    bedrooms: [1, 2, 3, 4],
    sqftMin: 1540,
    sqftMax: 3654,
    pricingFrom: '1BR-4BR from $1.8M',
    priceFrom: 1800000,
    pricePerSqft: 2666,
    deliveryYear: 2027,
    deliveryLabel: '2027',
    deposit: '',
    amenities: [
      'Private marina & waterfront promenade',
      '10,000-SF signature waterfront restaurant',
      'Heated saline pool deck with cabanas & outdoor spa',
      'Grand Salon for private events',
      'Club room',
      'Fitness center curated by Altitude Fitness',
      'Hammam spa',
      'Movie theater',
      'Kids\' playroom',
      'Wine cellar',
      'Pet spa',
      'Hair salon',
    ],
    parkingSpaces: '24-hour complimentary valet plus optional self-parking in assigned spaces, covered secured garage',
    description: 'Related Group\'s Baccarat Residences rises 75 stories where the Miami River meets Biscayne Bay in Brickell, with Arquitectonica architecture and full Baccarat-brand five-star service — house limousine, 24-hour room service, personal shopping. Museum-quality art curates the common areas, and the 12th-floor amenities deck anchors the resort-style program.',
    views: 'Miami River and Biscayne Bay at the river\'s mouth',
    waterfront: true,
    shortTermRental: false,
    constructionStatus: 'Under construction — vertical ascent toward 75-story apex, 2026',
    badge: 'TOP PICK',
    photos: [],
  },
  {
    id: 'waldorf-astoria-residences-miami',
    name: 'Waldorf Astoria Residences Miami',
    address: '300 Biscayne Boulevard',
    area: 'Downtown Miami',
    city: 'Miami',
    tagline: '',
    developer: 'Property Markets Group (PMG) & Greybrook Realty Partners',
    architecture: 'Carlos Ott with Sieger Suarez Architects',
    interiors: 'BAMO',
    stories: 100,
    totalUnits: 360,
    bedrooms: [0, 1, 2, 3, 4],
    sqftMin: 516,
    sqftMax: 12300,
    pricingFrom: 'Junior Suite Studios from ~$1.2M',
    priceFrom: 1200000,
    pricePerSqft: 1800,
    deliveryYear: 2028,
    deliveryLabel: '2027-2028',
    deposit: '20% at contract, 10% 30 days after, 10% 90 days after, 10% at one year, balance at closing',
    amenities: [
      'Private pool deck with whirlpools',
      'Private porte cochère',
      '24-hour lobby',
      'Fitness center with private training studios',
      'Lounge with bay views',
      'Signature restaurant',
      'Waldorf Astoria hotel rental program',
    ],
    parkingSpaces: 'Valet parking included for all residences',
    description: 'At 1,049 feet and 100 stories, Waldorf Astoria Hotel & Residences Miami is the city\'s first supertall skyscraper — nine staggered glass cubes designed with Carlos Ott and Sieger Suarez, interiors by BAMO. 360 condo residences sit above a 205-key Waldorf Astoria hotel, with construction past the 50th floor.',
    views: 'Biscayne Bay and full Downtown/Brickell skyline',
    waterfront: true,
    shortTermRental: true,
    constructionStatus: 'Under construction — superstructure past 50th floor',
    badge: 'TALLEST IN FLORIDA',
    photos: [],
  },
  {
    id: 'one-twenty-brickell-signature-residences',
    name: 'One Twenty Brickell Signature Residences',
    address: '120 SW 8th Street',
    area: 'Brickell',
    city: 'Miami',
    tagline: '',
    developer: 'Property Markets Group (PMG)',
    architecture: 'Sieger Suarez Architects',
    interiors: 'Cotofana Designs',
    stories: 40,
    totalUnits: 467,
    bedrooms: [0, 1, 2, 3],
    sqftMin: 451,
    sqftMax: 1294,
    pricingFrom: 'Studios from $650K | 1BR from $720K | 2BR from $1.2M | 3BR from $1.5M',
    priceFrom: 650000,
    pricePerSqft: 1300,
    deliveryYear: 2028,
    deliveryLabel: '2028',
    deposit: '10% at contract, 10% October 2026, 10% June 2027',
    amenities: [
      'Signature Club private owners\' lounge',
      'Resort-style pool with skyline views',
      'Wellness center with steam, sauna, plunge pools',
      'Treatment rooms',
      'Fitness studio',
      'Movement studio',
      'Café and juice bar',
      'Conference rooms',
      'Individually deeded private office suites',
    ],
    parkingSpaces: '1 free valet space per residence; 3-bedroom residences include an assigned self-parking space',
    description: 'PMG launched Signature Residences after fully selling out the first One Twenty Brickell tower. This 40-story companion pairs fully-furnished studios through 3-bedrooms with individually deeded private office suites — a live-work concept aimed at remote-work luxury buyers in the heart of Brickell.',
    views: 'Brickell and Downtown Miami skyline',
    waterfront: false,
    shortTermRental: false,
    constructionStatus: 'Preconstruction — sales launched April 2026',
    badge: '',
    photos: [
      'https://onetwentyresidences.com/wp-content/uploads/2026/04/Background-Image-Hero-Landing.webp',
      'https://onetwentyresidences.com/wp-content/uploads/2026/04/OTW2_NorthEast-View-Beam-1.webp',
    ],
  },
  {
    id: 'mercedes-benz-places-miami',
    name: 'Mercedes-Benz Places Miami',
    address: '1 Southside Park',
    area: 'Brickell',
    city: 'Miami',
    tagline: '',
    developer: 'JDS Development Group',
    architecture: 'SHoP Architects',
    interiors: 'Woods Bagot',
    stories: 67,
    totalUnits: 791,
    bedrooms: [0, 1, 2, 3],
    sqftMin: null,
    sqftMax: null,
    pricingFrom: 'Studios from ~$755K | 1BR from $1.2M | 2BR from $1.5M | 3BR from $2.7M',
    priceFrom: 755000,
    pricePerSqft: null,
    deliveryYear: 2028,
    deliveryLabel: 'Initial occupancy 2027; full delivery 2028',
    deposit: '20% at contract, 10% six months later, 10% at your floor, 10% at top-off, 50% at closing',
    amenities: [
      'Office space',
      'Full-service spa',
      'Full-service restaurant',
      'Banquet hall',
      'Fitness center',
      '130,000 SF of amenity and hospitality space',
      '174-key hotel',
      'Field Operations-designed public park',
    ],
    parkingSpaces: 'Up to 1,000 parking spaces across the development',
    description: 'Mercedes-Benz\'s first US residential skyscraper, designed by SHoP Architects with interiors by Woods Bagot — a cube-stacked 67-story West Brickell tower embodying the brand\'s \'Sensual Purity\' design language, with condos, offices, wellness space, and a branded hotel.',
    views: 'Brickell skyline and Miami River',
    waterfront: false,
    shortTermRental: false,
    constructionStatus: 'Under construction',
    badge: '',
    photos: [
      'https://miami.mercedesbenzplaces.com/wp-content/uploads/2024/02/Hero-East-Mercedes-Benz-Places-Miami-JDS-Development-Group-by-The-Boundary-scaled.jpg',
      'https://miami.mercedesbenzplaces.com/wp-content/uploads/2024/04/INT02_Kitchen-L-Shaped_Marble_Floor_B10-scaled.jpg',
      'https://miami.mercedesbenzplaces.com/wp-content/uploads/2024/04/EXT07_Pool-Aerial_v08-with-people-scaled.jpg',
      'https://miami.mercedesbenzplaces.com/wp-content/uploads/2024/04/EXT09_Waterliles_WithPeople_B8-scaled.jpg',
      'https://miami.mercedesbenzplaces.com/wp-content/uploads/2025/02/26.-Reception-Lobby-Mercedes-Benz-Places-in-Miami-JDS-Development-Group-by-The-Boundary-1-scaled.jpg',
    ],
  },
  {
    id: 'delano-residences-miami',
    name: 'Delano Residences Miami',
    address: '400 Biscayne Boulevard',
    area: 'Downtown Miami',
    city: 'Miami',
    tagline: '',
    developer: 'PMG & Ennismore',
    architecture: 'Carlos Ott',
    interiors: '',
    stories: 90,
    totalUnits: 421,
    bedrooms: [0, 1, 2, 3],
    sqftMin: 410,
    sqftMax: null,
    pricingFrom: 'From the $800,000s',
    priceFrom: 800000,
    pricePerSqft: null,
    deliveryYear: 2031,
    deliveryLabel: 'Targeting 2031 (groundbreaking Summer 2027)',
    deposit: '10% at contract, 10% October 2026, 10% at groundbreaking (Summer 2027), 10% one year after',
    amenities: [
      'Legendary Rose Bar',
      'Café Delano',
      'All-day signature restaurant',
      'Sky restaurant at 800+ feet',
      'The Source by Delano spa with steam, sauna, cold plunge',
      'Resort-style pool deck with cabanas over Biscayne Bay',
      'Sky pool at 800 feet',
      'Public observation deck at 850+ feet',
      'Delano Members\' Club',
    ],
    parkingSpaces: 'Full-service parking with signature porte-cochère drop-off and valet',
    description: 'PMG and Ennismore\'s first Delano-branded residential supertall — 90 stories and 985 feet directly across from Biscayne Bay in Downtown Miami, aiming to be the city\'s tallest observation-deck building. Sales launched early 2026; an early-innings, long-horizon preconstruction play with iconic hospitality branding.',
    views: 'Biscayne Bay and full Downtown/Brickell skyline from 850+ feet',
    waterfront: true,
    shortTermRental: false,
    constructionStatus: 'Preconstruction — sales just launched, groundbreaking targeted Summer 2027',
    badge: '',
    photos: [
      'https://delanomiamiresidences.com/wp-content/uploads/2026/06/PMG-Delano-01-Pool-09-1.webp',
      'https://delanomiamiresidences.com/wp-content/uploads/2026/06/Miamis-First-Ever-Observation-Deck.webp',
      'https://delanomiamiresidences.com/wp-content/uploads/2026/06/PMG-Delano-02-Unit_R1_Dining-02-1.webp',
      'https://delanomiamiresidences.com/wp-content/uploads/2026/06/PMG-Delano-03-Office-02-2.webp',
    ],
  },
  {
    id: 'casa-bella-residences-by-b-b-italia',
    name: 'Casa Bella Residences by B&B Italia',
    address: '1444 Biscayne Boulevard',
    area: 'Downtown Miami',
    city: 'Miami',
    tagline: '',
    developer: 'Related Group & Alta Developers',
    architecture: 'Arquitectonica',
    interiors: 'Piero Lissoni / B&B Italia',
    stories: 57,
    totalUnits: 306,
    bedrooms: [1, 2, 3, 4],
    sqftMin: 711,
    sqftMax: 5890,
    pricingFrom: '1BR from ~$660K | 3BR from ~$1.47M | 4BR penthouses up to $3.59M',
    priceFrom: 659900,
    pricePerSqft: null,
    deliveryYear: 2026,
    deliveryLabel: 'Q2 2026',
    deposit: '20% at contract, 10% at groundbreaking, 10% at top-off, 60% at closing',
    amenities: [
      'Two-level amenity program',
      'Rooftop pool deck over Biscayne Bay',
      'Landscape by Enzo Enea',
      'B&B Italia-furnished interiors',
      'Fitness center',
      'Spa',
      'Co-working lounge',
    ],
    parkingSpaces: 'PH/4BR: 2 spaces; 3BR: 2 tandem spaces; 2BR: 1 assigned + 1 valet',
    description: 'B&B Italia\'s residential debut in Miami\'s Arts & Entertainment District — a 57-story Arquitectonica tower with interiors led by Piero Lissoni, blending Milanese furniture-house design DNA with Biscayne Bay views.',
    views: 'Biscayne Bay and Downtown Miami skyline',
    waterfront: true,
    shortTermRental: false,
    constructionStatus: 'Under construction — final phase, nearing Q2 2026 delivery',
    badge: '',
    photos: [
      'https://casabellaresidences.com/wp-content/uploads/2022/01/Casa-Bella-Building.jpg',
    ],
  },
  {
    id: 'e11even-residences-beyond',
    name: 'E11EVEN Residences Beyond',
    address: '60 NE 11th Street',
    area: 'Downtown Miami',
    city: 'Miami',
    tagline: '',
    developer: 'Property Markets Group (PMG) & E11EVEN Partners',
    architecture: '',
    interiors: '',
    stories: 65,
    totalUnits: 461,
    bedrooms: [0, 1, 2],
    sqftMin: 385,
    sqftMax: 2675,
    pricingFrom: 'Studios from $300K | 2BR penthouses from $8.5M',
    priceFrom: 300000,
    pricePerSqft: null,
    deliveryYear: 2027,
    deliveryLabel: '2027',
    deposit: '',
    amenities: [
      'Private rooftop helipad',
      'Signature restaurant',
      '93-foot resort pool with private lounge areas',
      'Beach club',
      'Members-only Clayton social club',
      'Chopra Spa & Studio',
      'E11EVEN day club and pool',
      'Casino-style sports lounge',
      'Five-star restaurant collection by Riviera Dining Group',
    ],
    parkingSpaces: 'Valet services with dedicated resident parking areas',
    description: 'PMG and E11EVEN Partners\' Vegas-style residential tower in Miami\'s Park West / Arts & Entertainment District, blocks from Miami Worldcenter — 65 stories of fully furnished studios through 2-bedrooms plus a limited penthouse collection, anchored by E11EVEN\'s nightlife/hospitality brand.',
    views: 'Downtown Miami and Biscayne Bay skyline',
    waterfront: false,
    shortTermRental: true,
    constructionStatus: 'Under construction — approaching topping-out',
    badge: '',
    photos: [
      'https://e11evenresidences.com/app/uploads/2021/04/tru2314756-1.png',
      'https://e11evenresidences.com/app/uploads/2021/04/tru2599058-1.png',
      'https://e11evenresidences.com/app/uploads/2021/04/tru2345429-1.png',
    ],
  },
  {
    id: 'palm-tree-residences-miami',
    name: 'Palm Tree Residences Miami',
    address: '1018 North Miami Avenue',
    area: 'Downtown Miami',
    city: 'Miami',
    tagline: '',
    developer: 'PMG, Lion Development Group, EDEN Residential & Sterling Equities',
    architecture: 'Kobi Karp Architecture & Interior Design',
    interiors: '',
    stories: 37,
    totalUnits: 483,
    bedrooms: [0, 1, 2, 3],
    sqftMin: 478,
    sqftMax: 1209,
    pricingFrom: 'Studios from $500K | Jr Suite+Den from $700K | 2BR from $900K | 3BR from $1.4M',
    priceFrom: 500000,
    pricePerSqft: null,
    deliveryYear: 2030,
    deliveryLabel: 'Groundbreaking April 2027; completion ~2030',
    deposit: '',
    amenities: [
      '57,000+ SF of amenities across 3 levels',
      'Valet parking',
      '24-hour front desk concierge & security',
      'Package storage',
      'Optional in-house laundry & cleaning service',
    ],
    parkingSpaces: 'Valet parking',
    description: 'A festival-branded (Palm Tree) 37-story Park West / Downtown tower from PMG and partners, positioned as experiential, lifestyle-driven living adjacent to E11EVEN\'s residential towers. Fully furnished studios through 3-bedrooms with an entry price well under $1M.',
    views: 'Downtown Miami skyline',
    waterfront: false,
    shortTermRental: false,
    constructionStatus: 'Planned / preconstruction — groundbreaking targeted April 2027',
    badge: '',
    photos: [
      'https://www.miamicondoinvestments.com/wp-content/uploads/2026/05/palm-tree-residences-miami-01.jpg',
      'https://www.miamicondoinvestments.com/wp-content/uploads/2026/05/palm-tree-residences-miami-03.jpg',
      'https://www.miamicondoinvestments.com/wp-content/uploads/2026/05/palm-tree-residences-miami-05.jpg',
      'https://www.miamicondoinvestments.com/wp-content/uploads/2026/05/palm-tree-residences-miami-07.jpg',
    ],
  },
  {
    id: 'villa-miami',
    name: 'Villa Miami',
    address: '710 NE 29th Street',
    area: 'Edgewater',
    city: 'Miami',
    tagline: '',
    developer: 'Terra Group & One Thousand Group',
    architecture: 'ODP Architects',
    interiors: 'Vicky Charles',
    stories: 56,
    totalUnits: 70,
    bedrooms: [3, 4, 5, 6],
    sqftMin: 2936,
    sqftMax: 13498,
    pricingFrom: '3BR from $5.7M | full-floor from $6M',
    priceFrom: 5700000,
    pricePerSqft: 1650,
    deliveryYear: 2027,
    deliveryLabel: 'Late 2027 (Q2 2028)',
    deposit: '20% at contract, 10% at 90 days, 10% at 180 days, 10% at top-off, 50% at closing (Q2 2028)',
    amenities: [
      '20,000+ SF of amenities across 3 levels',
      'Major Food Group restaurant and bar',
      'Rooftop pool and lounge',
      'Full-service spa',
      'Private marina with boat docks',
      'Rooftop helipad',
      'Children\'s play area',
      'Library',
      'Fitness center',
      'Wine cellar',
      '24-hour concierge',
      'Direct Baywalk access',
    ],
    parkingSpaces: '160 spaces in a separate 9-story garage; valet service available',
    description: 'Major Food Group\'s first-ever branded residential tower — only 70 half- and full-floor residences across 56 stories on Biscayne Bay in Edgewater, with interiors by AD100 designer Vicky Charles. Two MFG dining concepts, a floating pool, and private docks anchor the amenity program.',
    views: 'Direct, unobstructed Biscayne Bay views, east-west flow-through',
    waterfront: true,
    shortTermRental: false,
    constructionStatus: 'Under construction — 37th of 56 floors',
    badge: 'MOST EXCLUSIVE',
    photos: [
      'https://villamiamiliving.com/assets/hero-tower-BomaIk75.jpg',
      'https://villamiamiliving.com/assets/interior-living-C06Arghq.jpg',
      'https://villamiamiliving.com/assets/amenity-pool-D93XM0lw.jpg',
      'https://villamiamiliving.com/assets/amenity-dining-BDJxTyZd.jpg',
      'https://villamiamiliving.com/assets/location-aerial-CWFaJ-8p.jpg',
    ],
  },
  {
    id: 'lilli-miami-edgewater',
    name: 'LILLI Miami Edgewater',
    address: '717 NE 27th Street',
    area: 'Edgewater',
    city: 'Miami',
    tagline: '',
    developer: 'OKO Group',
    architecture: 'Adrian Smith + Gordon Gill Architecture',
    interiors: '',
    stories: 53,
    totalUnits: 117,
    bedrooms: [1, 2, 3, 4],
    sqftMin: 1340,
    sqftMax: 6850,
    pricingFrom: '1BR from $1.6M | 2BR from $3M | 3BR from $5M | 4BR from $7.7M',
    priceFrom: 1600000,
    pricePerSqft: null,
    deliveryYear: 2027,
    deliveryLabel: 'Groundbreaking Q2 2027',
    deposit: '10% at contract, 10% at 90 days, 10% at groundbreaking, 10% nine months post-groundbreaking, 50% at closing',
    amenities: [
      'Wellness-centered four-pillars program',
      'Fitness studio',
      'Spa with infrared sauna',
      'Cold plunge pools',
      'Treatment room',
      'Movement studio',
      'Waterfront garden',
      'Rooftop saltwater pool',
    ],
    parkingSpaces: '',
    description: 'Vlad Doronin\'s OKO Group brings a sinuous, wellness-first 53-story bayfront tower to Edgewater, designed by Adrian Smith + Gordon Gill. Just 117 boutique residences from 1-4 bedrooms plus garden estates and penthouses, with sales freshly launched in 2026.',
    views: 'Direct Biscayne Bay waterfront',
    waterfront: true,
    shortTermRental: false,
    constructionStatus: 'Preconstruction — sales launched 2026, groundbreaking Q2 2027',
    badge: '',
    photos: [
      'https://lillimiami.com/img-cache/oko_edgewater-miami_v8_aerialpool-45f6edcb.jpg.webp',
      'https://lillimiami.com/img-cache/260323-lilli-boat-182_lowres-1500x2000-60edee74.jpg.webp',
    ],
  },
  {
    id: 'twentysixth-2nd-wynwood',
    name: 'TwentySixth & 2nd Wynwood',
    address: '201 NW 26th Street',
    area: 'Wynwood',
    city: 'Miami',
    tagline: '',
    developer: 'PMG & LNDMRK Development',
    architecture: '',
    interiors: '',
    stories: 8,
    totalUnits: 233,
    bedrooms: [0, 1],
    sqftMin: null,
    sqftMax: null,
    pricingFrom: 'Studios/junior suites from $500K | larger from $700K',
    priceFrom: 500000,
    pricePerSqft: null,
    deliveryYear: 2028,
    deliveryLabel: 'Q2 2028',
    deposit: '',
    amenities: [
      '32,000 SF wellness-inspired amenities',
      'Meditation glass house',
      'Thermal circuit with steam, sauna, cold plunge',
      'Private treatment rooms',
      'Fitness studio',
      'Sky Swim Lounge rooftop pool with cabanas',
      'Outdoor bar and lounge',
      '24-hour valet',
      'Sports equipment storage',
    ],
    parkingSpaces: 'Private residential porte cochère with 24-hour valet service',
    description: 'PMG and LNDMRK\'s boutique 8-story Wynwood tower pairs 233 fully furnished residences with 122 deeded, fully equipped office suites — the first Miami development explicitly marketed for Airbnb hosting flexibility on those office-suite units. Broke ground May 2026.',
    views: 'Wynwood streetscape / partial skyline on upper floors',
    waterfront: false,
    shortTermRental: true,
    constructionStatus: 'Under construction — broke ground May 2026',
    badge: '',
    photos: [
      'https://26thand2nd.miami/assets/images/image01.png',
      'https://26thand2nd.miami/assets/images/image03.jpg',
      'https://26thand2nd.miami/assets/images/image05.jpg',
      'https://26thand2nd.miami/assets/images/image09.jpg',
    ],
  },
  {
    id: 'bentley-residences-sunny-isles-beach',
    name: 'Bentley Residences Sunny Isles Beach',
    address: '18401 Collins Avenue',
    area: 'Sunny Isles Beach',
    city: 'Sunny Isles Beach',
    tagline: '',
    developer: 'Dezer Development',
    architecture: 'Sieger Suarez Architects',
    interiors: 'Bentley Home',
    stories: 62,
    totalUnits: 216,
    bedrooms: [3, 4],
    sqftMin: 3015,
    sqftMax: null,
    pricingFrom: 'From ~$8.85M; penthouse listed at $37.5M',
    priceFrom: 8850000,
    pricePerSqft: 2935,
    deliveryYear: 2028,
    deliveryLabel: 'Q1 2028',
    deposit: '',
    amenities: [
      'In-unit multi-car garage via patented Dezervator vehicular elevator',
      'Private pool & sauna option in select residences',
      'Whiskey bar',
      'Cigar lounge',
      'Cinema',
      'Wellness spa',
      'Oceanfront pool deck',
      'Private restaurant curated by chef Todd English',
      'Fitness center',
      'Cabanas',
    ],
    parkingSpaces: 'Private 3- or 4-car garage per residence (Dezervator car elevator)',
    description: 'The world\'s first Bentley-branded residential tower, rising 749 feet directly on the sand in Sunny Isles Beach. Each of the 216 sky mansions is delivered with its own in-unit garage — cars are parked inside the residence itself via a patented elevator. Interiors are curated by Bentley\'s own design studio.',
    views: 'Direct Atlantic Ocean and Intracoastal views',
    waterfront: true,
    shortTermRental: false,
    constructionStatus: 'Under construction — sales active, delivery Q1 2028',
    badge: '',
    photos: [
      'https://imgprd.condoblackbook.com/buildings/1999/images/100176360_medium.webp',
      'https://imgprd.condoblackbook.com/buildings/1999/images/100179746_medium.webp',
    ],
  },
  {
    id: 'the-st-regis-residences-sunny-isles-beach',
    name: 'The St. Regis Residences, Sunny Isles Beach',
    address: '18801 Collins Avenue',
    area: 'Sunny Isles Beach',
    city: 'Sunny Isles Beach',
    tagline: '',
    developer: 'Fortune International Group and Château Group',
    architecture: 'Arquitectonica',
    interiors: 'Patricia Anastassiadis',
    stories: 62,
    totalUnits: 336,
    bedrooms: [2, 3, 4, 5],
    sqftMin: 1848,
    sqftMax: 5156,
    pricingFrom: 'South Tower 2BR+Den from $6.15M; North Tower 2BR from $5.0M',
    priceFrom: 5000000,
    pricePerSqft: null,
    deliveryYear: 2028,
    deliveryLabel: 'South Tower Q4 2028; North Tower Q4 2029',
    deposit: '',
    amenities: [
      'Club members pool, tower pool & lap pool',
      'Two restaurants',
      '70,000 sq ft of amenities',
      'Private dining with chef\'s kitchen',
      'Housekeeping & butler service',
      'Private elevator/foyer per unit',
      'Sky villas with private pools & jacuzzis',
      'Spa & wellness center',
    ],
    parkingSpaces: '',
    description: 'Twin 62-story oceanfront towers bringing St. Regis\'s signature butler service and yacht-inspired Arquitectonica design to over 400 feet of Sunny Isles Beach frontage. South Tower is nearly sold out and under construction; North Tower broke ground in 2026 with 70,000 sq ft of shared amenities.',
    views: 'Direct Atlantic Ocean frontage',
    waterfront: true,
    shortTermRental: false,
    constructionStatus: 'South Tower under construction (near sold-out); North Tower broke ground 2026',
    badge: '',
    photos: [
      'https://imgprd.condoblackbook.com/buildings/2117/images/100218105_medium.webp',
      'https://imgprd.condoblackbook.com/buildings/2117/images/100218126_medium.webp',
    ],
  },
  {
    id: 'rivage-bal-harbour',
    name: 'Rivage Bal Harbour',
    address: '10245 Collins Avenue',
    area: 'Bal Harbour',
    city: 'Bal Harbour',
    tagline: '',
    developer: 'Related Group, Two Roads Development, Rockpoint',
    architecture: 'Skidmore, Owings & Merrill (SOM)',
    interiors: 'Rottet Studio',
    stories: 25,
    totalUnits: 56,
    bedrooms: [3, 4],
    sqftMin: 3300,
    sqftMax: 13000,
    pricingFrom: 'From $8M to $64M',
    priceFrom: 8000000,
    pricePerSqft: 3800,
    deliveryYear: 2027,
    deliveryLabel: '2027',
    deposit: '',
    amenities: [
      'SOM-designed glass tower on 275 ft of oceanfront',
      'Rottet Studio interiors',
      'Enea Garden Design landscaping',
      'Beach club',
      'Full-service spa',
      'Multiple pools',
    ],
    parkingSpaces: '',
    description: 'A 275-foot glass oceanfront tower designed by SOM — widely described as the last new oceanfront development site in Bal Harbour. Just 56 bespoke beachfront residences, from 3,300 sq ft to 13,000 sq ft penthouses, with interiors by Rottet Studio.',
    views: 'Direct Atlantic Ocean views',
    waterfront: true,
    shortTermRental: false,
    constructionStatus: 'Under construction (broke ground September 2024)',
    badge: '',
    photos: [
      'https://rivagebalharbour.com/wp-content/uploads/2026/02/Beach_Sunset.jpg',
      'https://rivagebalharbour.com/wp-content/uploads/2024/02/Boat.jpg',
      'https://imgprd.condoblackbook.com/buildings/2168/images/100198980_medium.webp',
    ],
  },
  {
    id: 'the-delmore',
    name: 'The Delmore',
    address: '8777 Collins Avenue',
    area: 'Surfside',
    city: 'Surfside',
    tagline: '',
    developer: 'DAMAC International',
    architecture: 'Zaha Hadid Architects',
    interiors: 'Hirsch Bedner Associates',
    stories: 12,
    totalUnits: 37,
    bedrooms: [4, 5, 6, 7],
    sqftMin: 4400,
    sqftMax: 8724,
    pricingFrom: 'From $15M; penthouse up to $145M',
    priceFrom: 15000000,
    pricePerSqft: null,
    deliveryYear: 2029,
    deliveryLabel: '2029',
    deposit: '',
    amenities: [
      'Zaha Hadid sculptural facade — no more than 4 residences per floor',
      'Fully furnished sky-mansion residences',
      'Dual kitchens',
      'Wraparound terraces',
      'Butler service',
      'Oceanfront pool deck',
      'Spa & wellness center',
    ],
    parkingSpaces: '',
    description: 'Often called Miami\'s first true billionaire condo building — a 12-story sculptural masterpiece by the late Zaha Hadid, with just 37 fully furnished sky-mansion residences starting at 4,400 sq ft. Interiors by Hirsch Bedner Associates on the Surfside oceanfront.',
    views: 'Direct Atlantic Ocean views',
    waterfront: true,
    shortTermRental: false,
    constructionStatus: 'Preconstruction — foundation phase complete, vertical construction pending',
    badge: '',
    photos: [
      'https://imgprd.condoblackbook.com/buildings/2307/images/100214682_medium.webp',
      'https://imgprd.condoblackbook.com/buildings/2307/images/100214694_medium.webp',
      'https://imgprd.condoblackbook.com/buildings/2307/images/100214706_medium.webp',
    ],
  },
  {
    id: 'ocean-house-residences-surfside',
    name: 'Ocean House Residences Surfside',
    address: '9317 Collins Avenue',
    area: 'Surfside',
    city: 'Surfside',
    tagline: '',
    developer: 'Multiplan Real Estate Asset Management (REAM)',
    architecture: 'Arquitectonica',
    interiors: 'Carla Guilhem Design',
    stories: 11,
    totalUnits: 25,
    bedrooms: [2, 3, 4, 5],
    sqftMin: 2093,
    sqftMax: 7143,
    pricingFrom: 'From ~$5.1M',
    priceFrom: 5100000,
    pricePerSqft: 4051,
    deliveryYear: 2027,
    deliveryLabel: '2027',
    deposit: '',
    amenities: [
      'Rooftop pool & spa',
      'Floating cabanas',
      'Fitness center',
      '24-hour valet parking',
      'EV charging stations',
      'Double-height lobby with custom stone reception',
      'Private elevators with dedicated lobbies',
      'Outdoor kitchen',
    ],
    parkingSpaces: '24-hour valet',
    description: 'A boutique 25-residence oceanfront tower on Surfside\'s Collins Avenue corridor by Arquitectonica, offering 2- to 5-bedroom homes from roughly 2,100 to over 7,100 sq ft, with Gaggenau appliances, natural stone, and 10–12 ft ceilings with impact glass.',
    views: 'Direct Atlantic Ocean views',
    waterfront: true,
    shortTermRental: false,
    constructionStatus: 'Under construction',
    badge: '',
    photos: [
      'https://imgprd.condoblackbook.com/buildings/2286/images/100208228_medium.webp',
      'https://imgprd.condoblackbook.com/buildings/2286/images/100208246_medium.webp',
      'https://imgprd.condoblackbook.com/buildings/2286/images/100208264_medium.webp',
    ],
  },
  {
    id: 'surf-row-residences',
    name: 'Surf Row Residences',
    address: '8800 Collins Avenue',
    area: 'Surfside',
    city: 'Surfside',
    tagline: '',
    developer: 'LD&D in partnership with ONE Capital and IGEQ',
    architecture: 'Alfonso Jurado Architecture and Boris Peña Architects',
    interiors: 'RH (Restoration Hardware)',
    stories: 3,
    totalUnits: 25,
    bedrooms: [1, 2, 3],
    sqftMin: 894,
    sqftMax: 2195,
    pricingFrom: 'From $1.375M',
    priceFrom: 1375000,
    pricePerSqft: null,
    deliveryYear: 2027,
    deliveryLabel: '2027',
    deposit: '',
    amenities: [
      'Rooftop pool deck with panoramic ocean views',
      'Zen spa with sauna and cold plunge',
      'Fitness studio',
      'Co-working spaces',
      'Beachside butler service',
    ],
    parkingSpaces: '',
    description: 'A collection of low-rise, single-family-style row residences directly on the Surfside beach, developed by LD&D with ONE Capital and IGEQ, outfitted with RH-curated interiors. An entry point into oceanfront Surfside living at a lower per-unit price than the area\'s high-rise towers.',
    views: 'Ocean views',
    waterfront: true,
    shortTermRental: false,
    constructionStatus: 'Under construction',
    badge: '',
    photos: [
      'https://imgprd.condoblackbook.com/buildings/2150/images/100224204_medium.webp',
      'https://imgprd.condoblackbook.com/buildings/2150/images/100224213_medium.webp',
      'https://imgprd.condoblackbook.com/buildings/2150/images/100224222_medium.webp',
    ],
  },
  {
    id: 'aman-miami-beach-residences',
    name: 'Aman Miami Beach Residences',
    address: '3425 Collins Avenue',
    area: 'Miami Beach',
    city: 'Miami Beach',
    tagline: '',
    developer: 'OKO Group + Aman, with Access Industries',
    architecture: 'Kengo Kuma',
    interiors: 'Jean-Michel Gathy',
    stories: 18,
    totalUnits: 22,
    bedrooms: [1, 2, 3, 4, 5, 6],
    sqftMin: null,
    sqftMax: null,
    pricingFrom: 'From $4M',
    priceFrom: 4000000,
    pricePerSqft: 2000,
    deliveryYear: 2027,
    deliveryLabel: '2026–2027',
    deposit: '',
    amenities: [
      'Aman Club',
      'Aman Spa',
      'Multiple dining venues',
      'Direct beach access',
      'Private pool',
    ],
    parkingSpaces: '',
    description: 'An intimate 22-residence oceanfront tower on the site of the historic Versailles Hotel in Miami Beach\'s Faena District, designed by Kengo Kuma. Full Aman hospitality — spa, dining, and Aman Club access — is built into ownership, with two- to six-bedroom layouts including full-floor and duplex penthouses.',
    views: 'Direct Atlantic Ocean views',
    waterfront: true,
    shortTermRental: false,
    constructionStatus: 'Under construction',
    badge: '',
    photos: [
      'https://imgprd.condoblackbook.com/buildings/1983/images/100170054_medium.webp',
      'https://imgprd.condoblackbook.com/buildings/1983/images/100170057_medium.webp',
      'https://imgprd.condoblackbook.com/buildings/1983/images/100170063_medium.webp',
    ],
  },
  {
    id: 'the-perigon-miami-beach',
    name: 'The Perigon Miami Beach',
    address: '5333 Collins Avenue',
    area: 'Miami Beach',
    city: 'Miami Beach',
    tagline: '',
    developer: 'Mast Capital and Starwood Capital Group',
    architecture: 'OMA (Rem Koolhaas / Reinier de Graaf)',
    interiors: 'Tara Bernerd & Partners',
    stories: 18,
    totalUnits: 83,
    bedrooms: [2, 3, 4],
    sqftMin: 2100,
    sqftMax: 6700,
    pricingFrom: '2BR from $4.25M; 3BR from $7.55M; 4BR from $9.52M',
    priceFrom: 4250000,
    pricePerSqft: null,
    deliveryYear: 2026,
    deliveryLabel: 'Q4 2026–Q1 2027',
    deposit: '',
    amenities: [
      'Oceanfront restaurant',
      'Beachside pool',
      'Outdoor spa with sunbeds & cabanas',
      'Direct beach access',
      'Screening room',
      'Fitness center & sauna',
      'Billiards room',
      'Wine room',
      'Porte cochère',
    ],
    parkingSpaces: '',
    description: 'An 18-story, 83-residence oceanfront tower in mid-Beach designed by Rem Koolhaas\'s OMA, one of the most architecturally significant new towers on the barrier island. Interiors by Tara Bernerd & Partners with custom Italian kitchens. Well advanced, selling remaining inventory and penthouses.',
    views: 'Direct Atlantic Ocean views',
    waterfront: true,
    shortTermRental: false,
    constructionStatus: 'Under construction, near completion',
    badge: '',
    photos: [
      'https://imgprd.condoblackbook.com/medium_Building_from_the_Sand_19bf458bb1.webp',
      'https://imgprd.condoblackbook.com/medium_Hero_Hummingbird_8916f0aa24.webp',
      'https://imgprd.condoblackbook.com/medium_Pool_To_Beach_R03_5k_c232ddb100.webp',
      'https://imgprd.condoblackbook.com/medium_Great_Room_b168311712.webp',
    ],
  },
  {
    id: 'rosewood-residences-at-the-raleigh',
    name: 'Rosewood Residences at The Raleigh',
    address: '1775 Collins Avenue',
    area: 'Miami Beach',
    city: 'Miami Beach',
    tagline: '',
    developer: 'SHVO',
    architecture: 'Kobi Karp',
    interiors: 'Peter Marino',
    stories: 17,
    totalUnits: 40,
    bedrooms: [2, 3, 4, 5, 6, 7],
    sqftMin: 2100,
    sqftMax: 13218,
    pricingFrom: '3BR from $10M',
    priceFrom: 10000000,
    pricePerSqft: null,
    deliveryYear: 2027,
    deliveryLabel: '2026–2027',
    deposit: '',
    amenities: [
      'Three-acre beachfront grounds, 220 ft of ocean frontage',
      'Private members club with beachfront dining',
      'Resort-style pool',
      'Natural limestone pool deck',
      'Rosewood Hotels & Resorts bespoke services',
      'Valet with covered parking',
      'Hand-painted millwork and artisan plaster interiors',
    ],
    parkingSpaces: 'Valet, covered parking',
    description: 'SHVO\'s full restoration of the historic Art Deco Raleigh Hotel paired with a new 17-story Rosewood-branded tower — Peter Marino designed all 40 interiors himself. Set on three beachfront acres with 220 feet of ocean frontage in South Beach.',
    views: 'Direct Atlantic Ocean views',
    waterfront: true,
    shortTermRental: false,
    constructionStatus: 'Under construction',
    badge: '',
    photos: [
      'https://imgprd.condoblackbook.com/buildings/2131/images/100206056_medium.webp',
      'https://imgprd.condoblackbook.com/buildings/2131/images/100182032_medium.webp',
      'https://imgprd.condoblackbook.com/buildings/2131/images/100206065_medium.webp',
    ],
  },
  {
    id: 'shore-club-private-collection',
    name: 'Shore Club Private Collection',
    address: '1901 Collins Avenue',
    area: 'Miami Beach',
    city: 'Miami Beach',
    tagline: '',
    developer: 'Witkoff and Monroe Capital, with Auberge Resorts',
    architecture: 'Robert A.M. Stern Architects',
    interiors: 'Robert A.M. Stern Architects',
    stories: 18,
    totalUnits: 49,
    bedrooms: [2, 3, 4, 5, 6],
    sqftMin: 1900,
    sqftMax: 10500,
    pricingFrom: 'From ~$6M; penthouses from ~$35M',
    priceFrom: 6000000,
    pricePerSqft: null,
    deliveryYear: 2027,
    deliveryLabel: '2027',
    deposit: '',
    amenities: [
      'Full Auberge Resorts hospitality — butler service, personal chef access',
      '24-hour concierge',
      'Full-service spa and beauty atelier',
      'Housekeeping',
      'Dedicated Director of Residences',
      '3-acre oceanfront estate across three buildings',
    ],
    parkingSpaces: '',
    description: 'A reimagining of the landmark Art Deco Shore Club by Witkoff and Robert A.M. Stern, spread across a rare 3-acre oceanfront estate in South Beach. Only 49 residences split between an 18-story tower, the boutique Cromwell House, and a single Beach House, all serviced by Auberge Resorts Collection.',
    views: 'Direct Atlantic Ocean views',
    waterfront: true,
    shortTermRental: false,
    constructionStatus: 'Under construction — concrete pour completed November 2025',
    badge: '',
    photos: [
      'https://cdn.sanity.io/images/7mh0bsjc/production/cc2bbc9aab919723f42219419bf83723155b75ab-6000x3376.jpg',
      'https://cdn.sanity.io/images/7mh0bsjc/production/b6838404cc87f7940c43341e4c78c376453dde54-6000x3376.jpg',
      'https://cdn.sanity.io/images/7mh0bsjc/production/acccb672becc4ce162abda33af97131f175c1b50-5000x3200.png',
    ],
  },
  {
    id: 'ocean-terrace-residences',
    name: 'Ocean Terrace Residences',
    address: '740 Ocean Terrace',
    area: 'Miami Beach',
    city: 'Miami Beach',
    tagline: '',
    developer: 'Witkoff and Ocean Terrace Holdings',
    architecture: 'Revuelta Architecture International',
    interiors: 'Robert A.M. Stern Architects',
    stories: 20,
    totalUnits: 76,
    bedrooms: [3, 4],
    sqftMin: null,
    sqftMax: null,
    pricingFrom: 'From ~$4M',
    priceFrom: 4000000,
    pricePerSqft: null,
    deliveryYear: 2029,
    deliveryLabel: '2029',
    deposit: '',
    amenities: [
      '350 linear feet of beachfront',
      'Art Deco preservation + new modernist tower',
      'Reimagined 42-key luxury hotel component',
      'Spa',
      'Multiple pools',
    ],
    parkingSpaces: '',
    description: 'A large-scale North Beach redevelopment by Witkoff blending new construction with restored Art Deco buildings across 350 feet of oceanfront. Combines a 20-story tower of 52 boutique condos with a second building of 24 resort residences and a 42-key hotel.',
    views: 'Direct Atlantic Ocean views',
    waterfront: true,
    shortTermRental: false,
    constructionStatus: 'Preconstruction — approved, delivery targeted 2029',
    badge: '',
    photos: [
      'https://imgprd.condoblackbook.com/buildings/2089/images/100225902_medium.webp',
      'https://imgprd.condoblackbook.com/buildings/2089/images/100225911_medium.webp',
      'https://imgprd.condoblackbook.com/buildings/2089/images/100225926_medium.webp',
    ],
  },
  {
    id: '7200-collins',
    name: '7200 Collins',
    address: '7200 Collins Avenue',
    area: 'Miami Beach',
    city: 'Miami Beach',
    tagline: '',
    developer: 'Amicon & Northlink Capital',
    architecture: 'Revuelta Architecture International',
    interiors: 'Adriana Hoyos Design Studio',
    stories: 12,
    totalUnits: 222,
    bedrooms: [0, 1, 2],
    sqftMin: 375,
    sqftMax: 1332,
    pricingFrom: 'Studios from $600Ks; 1BR from mid-$800Ks; 2BR+den from $2M',
    priceFrom: 600000,
    pricePerSqft: null,
    deliveryYear: 2027,
    deliveryLabel: '2027–2028',
    deposit: '20% at contract, 10% at groundbreaking, 10% at top-off, 60% at closing',
    amenities: [
      'Resort-style pool',
      'Fitness center',
      'Library lounge',
      'Yoga/meditation terrace',
      'Rooftop lounge with sundeck',
      'On-site retail/F&B',
      'Bicycle storage',
      'Landscaped gardens',
    ],
    parkingSpaces: '',
    description: 'North Beach\'s newest and most accessibly priced preconstruction oceanfront condo, breaking ground March 2026 with 222 studio-to-2BR+den residences designed by Revuelta Architecture. Unrestricted short-term rental flexibility (daily, weekly, or monthly) makes this a strong turnkey investment play.',
    views: 'Ocean and city views',
    waterfront: true,
    shortTermRental: true,
    constructionStatus: 'Preconstruction — broke ground March 2026',
    badge: 'BEST VALUE',
    photos: [
      'https://imgprd.condoblackbook.com/buildings/2324/images/100217151_medium.webp',
      'https://imgprd.condoblackbook.com/buildings/2324/images/100217163_medium.webp',
      'https://imgprd.condoblackbook.com/buildings/2324/images/100217184_medium.webp',
    ],
  },
  {
    id: 'bay-harbor-towers',
    name: 'Bay Harbor Towers',
    address: '10141 East Bay Harbor Drive',
    area: 'Bay Harbor Islands',
    city: 'Bay Harbor Islands',
    tagline: '',
    developer: 'PPG Development and L3C Capital Partners',
    architecture: 'Kobi Karp',
    interiors: 'Steven G.',
    stories: 8,
    totalUnits: 44,
    bedrooms: [2, 3, 4],
    sqftMin: 1870,
    sqftMax: 3393,
    pricingFrom: '2BR+Den from $2.5M',
    priceFrom: 2500000,
    pricePerSqft: null,
    deliveryYear: 2026,
    deliveryLabel: 'Q4 2026',
    deposit: '',
    amenities: [
      'Private marina',
      'Rooftop swimming pool',
      'Tropical garden',
      'Private wading pools (select units)',
      'Panoramic Biscayne Bay and Bal Harbour views',
    ],
    parkingSpaces: '',
    description: 'An 8-story, 44-residence waterfront condominium on the Indian Creek waterway in Bay Harbor Islands, designed by Kobi Karp with interiors by Steven G. Flow-through 2- to 4-bedroom+den layouts from roughly 1,870 to 3,393 sq ft, with select units offering private pools.',
    views: 'Biscayne Bay and Indian Creek waterway views',
    waterfront: true,
    shortTermRental: false,
    constructionStatus: 'Under construction — delivery Q4 2026',
    badge: '',
    photos: [
      'https://cdn.prod.website-files.com/635a9e5e26ec99e7bcef234a/64fb63b64549d64251f0e3b2_BHT%20New%20Rendering%20(View%20From%20Water)%20(2).jpg',
      'https://imgprd.condoblackbook.com/buildings/2222/images/100200585_medium.webp',
    ],
  },
  {
    id: 'bay-harbor-villas',
    name: 'Bay Harbor Villas',
    address: '10190 East Bay Harbor Drive',
    area: 'Bay Harbor Islands',
    city: 'Bay Harbor Islands',
    tagline: '',
    developer: 'Regency Development Group',
    architecture: 'Kobi Karp Architecture & Interior Design',
    interiors: 'Arhidiza',
    stories: 3,
    totalUnits: 13,
    bedrooms: [3, 4],
    sqftMin: 2375,
    sqftMax: 2976,
    pricingFrom: 'From $2.65M',
    priceFrom: 2650000,
    pricePerSqft: null,
    deliveryYear: 2026,
    deliveryLabel: 'Late 2026',
    deposit: '',
    amenities: [
      'Interior elevators to all levels',
      '2-car climate-controlled garages',
      'Italian kitchens by Armony Cucine',
      'Miele appliances',
      'Smart home pre-wiring',
      'Rooftop terraces',
      'Walk-in pantries',
    ],
    parkingSpaces: '2-car climate-controlled garage per residence',
    description: 'A boutique 13-townhome collection by Regency Development Group and Kobi Karp on Bay Harbor Islands\' waterfront corridor, offering 3- and 4-bedroom layouts of 2,375–2,976 sq ft with private 2-car garages and rooftop terraces.',
    views: 'Waterway/canal views',
    waterfront: true,
    shortTermRental: false,
    constructionStatus: 'Under construction — delivery late 2026',
    badge: '',
    photos: [
      'http://bayharborvillas.com/wp-content/uploads/2025/03/Aerial.jpg',
      'http://bayharborvillas.com/wp-content/uploads/2025/03/Interior.jpg',
      'http://bayharborvillas.com/wp-content/uploads/2025/03/Bedroom-1.jpg',
    ],
  },
  {
    id: 'viceroy-residences-aventura',
    name: 'Viceroy Residences Aventura',
    address: '2999 NE 191st Street',
    area: 'Aventura',
    city: 'Aventura',
    tagline: '',
    developer: 'Related Group & BH Group',
    architecture: 'Arquitectonica',
    interiors: 'DesignAgency',
    stories: 28,
    totalUnits: 274,
    bedrooms: [1, 2, 3, 4],
    sqftMin: 858,
    sqftMax: 2014,
    pricingFrom: 'From $925,000',
    priceFrom: 925000,
    pricePerSqft: null,
    deliveryYear: 2028,
    deliveryLabel: '2028',
    deposit: '',
    amenities: [
      '90-foot resort-style pool with spa and cabanas',
      'Hemingway Rooftop Bar & Lounge',
      'Fitness center',
      'Rock climbing wall',
      'Indoor sports courts (basketball & pickleball)',
      'Spa with sauna and plunge pools',
      'Golf simulator',
      'Children\'s playroom & teen gaming lounge',
      'Co-working center',
      'Pet spa',
    ],
    parkingSpaces: '',
    description: 'Viceroy Residences Aventura brings the hospitality brand\'s hotel-inspired lifestyle to a 28-story tower of 274 residences designed by Arquitectonica with interiors by DesignAgency. Floor-to-ceiling windows, expansive terraces, and Miele kitchens define the one- to four-bedroom layouts, with a resort-scale amenity deck and rooftop lounge.',
    views: 'Aventura city and golf-course area views',
    waterfront: false,
    shortTermRental: false,
    constructionStatus: 'Preconstruction — active pre-sales',
    badge: '',
    photos: [
      'https://www.miamicondoinvestments.com/wp-content/uploads/2025/03/Viceroy-Residences-Aventura.jpg',
      'https://www.miamicondoinvestments.com/wp-content/uploads/2025/03/Viceroy-Residences-Aventura-Living-Room.jpg',
      'https://www.miamicondoinvestments.com/wp-content/uploads/2025/03/Viceroy-Residences-Aventura-Pool-Deck.jpg',
    ],
  },
  {
    id: 'the-william-north-miami-beach',
    name: 'The William North Miami Beach',
    address: '2045 NE 163rd Street',
    area: 'North Miami Beach',
    city: 'North Miami Beach',
    tagline: '',
    developer: '',
    architecture: 'Carlos Ott with Behar Font & Partners',
    interiors: 'Urban Robot',
    stories: 26,
    totalUnits: 374,
    bedrooms: [0, 1, 2, 3],
    sqftMin: 590,
    sqftMax: 1420,
    pricingFrom: 'Studios from $380,900; 1BR from $412,900; 2BR from $598,900; 3BR from $990,900',
    priceFrom: 380900,
    pricePerSqft: null,
    deliveryYear: 2029,
    deliveryLabel: 'Groundbreaking mid-2026; completion Summer 2029',
    deposit: '10% at Reservation, 10% at Contract, 10% at Groundbreaking, 10% at Top Off, 60% at Closing',
    amenities: [
      '9th-floor resort-style pool with private cabanas',
      'Outdoor bar & terrace lounge with fire pits',
      'Fitness center with yoga studio',
      'Spa treatment rooms',
      'Alfresco dining/summer kitchen',
      '26th-floor rooftop pickleball court',
      'Coworking lounge & terrace library',
      'Kids playroom with outdoor playground',
      'Self-serve market',
      '24/7 valet & concierge',
      'EV charging',
    ],
    parkingSpaces: '',
    description: 'A 26-story, 374-residence tower by Carlos Ott with Behar Font & Partners, The William reinterprets North Miami Beach\'s midcentury heritage with a louvered facade and 40,000+ sq ft of amenities across two sky decks. Studio-to-three-bedroom layouts with interiors by Urban Robot are priced to capture entry-level luxury buyers.',
    views: 'City and skyline views',
    waterfront: false,
    shortTermRental: false,
    constructionStatus: 'Preconstruction — pre-sales open, groundbreaking expected mid-2026',
    badge: '',
    photos: [
      'https://www.thewilliamnorthmiamibeach.com/images/williams/rendering/The%20William_Exterior.webp',
      'https://www.thewilliamnorthmiamibeach.com/images/williams/rendering/The%20William_Hero.webp',
      'https://www.thewilliamnorthmiamibeach.com/images/williams/rendering/The%20William_Living%20Room.webp',
      'https://www.thewilliamnorthmiamibeach.com/images/williams/rendering/The%20William_Kitchen.webp',
    ],
  },
  {
    id: 'nexo-residences',
    name: 'Nexo Residences',
    address: '13899 Biscayne Boulevard',
    area: 'North Miami Beach',
    city: 'North Miami Beach',
    tagline: '',
    developer: 'Fortune International Group (with Blue Road)',
    architecture: 'Frankel Benayoun Architects',
    interiors: '',
    stories: 15,
    totalUnits: 254,
    bedrooms: [0, 1, 2, 3, 4],
    sqftMin: 531,
    sqftMax: 2464,
    pricingFrom: 'From the $599,000s',
    priceFrom: 599000,
    pricePerSqft: 929,
    deliveryYear: 2026,
    deliveryLabel: 'Q3 2026',
    deposit: '',
    amenities: [
      'Pool deck',
      'Fitness center',
      'Integrated short-term rental management program (AvantStay)',
    ],
    parkingSpaces: '',
    description: 'Nexo Residences is a 15-story, 254-unit tower along the Biscayne corridor built for flexible ownership — fully furnished studios through 4-bedroom townhomes designed for short-term, seasonal, or long-term rental with no restrictions. Topped off and ~90% pre-sold ahead of its Q3 2026 delivery.',
    views: 'Biscayne corridor views',
    waterfront: false,
    shortTermRental: true,
    constructionStatus: 'Topped off, under construction — ~90% pre-sold, limited remaining inventory',
    badge: '',
    photos: [
      'https://nexoresidencesmiami.com/wp-content/uploads/2023/06/homepage-top-1920x1080.jpg',
      'https://nexoresidencesmiami.com/wp-content/uploads/2023/06/Building-Townhome-I-Nexo-Residences.jpg',
      'https://nexoresidencesmiami.com/wp-content/uploads/2023/06/FORCT_04_Pool-Deck_High_people.png',
    ],
  },
  {
    id: 'four-seasons-private-residences-coconut-grove',
    name: 'Four Seasons Private Residences Coconut Grove',
    address: '2699 South Bayshore Drive',
    area: 'Coconut Grove',
    city: 'Miami',
    tagline: '',
    developer: 'CMC Group & Fort Partners',
    architecture: 'Revuelta Architecture International',
    interiors: 'Michele Bönan',
    stories: 20,
    totalUnits: 70,
    bedrooms: [2, 3, 4],
    sqftMin: null,
    sqftMax: null,
    pricingFrom: '2BR from $5.6M; 3BR from $8.1M; 4BR+Den from $12.1M',
    priceFrom: 5600000,
    pricePerSqft: null,
    deliveryYear: 2028,
    deliveryLabel: '2028',
    deposit: '',
    amenities: [
      'Dedicated pool deck with bar lounge',
      'Spa and wellness center with indoor pool',
      'Roman bath \'Caesar Experience\' — five temperature-controlled rooms',
      'Finnish saunas',
      'Fitness center with gym and yoga studio',
      'Residents\' library',
      'Residents-only bar lounge',
      'Concierge services',
    ],
    parkingSpaces: '',
    description: 'Miami\'s first Four Seasons-branded private residences bring the group\'s ultra-luxury service model to Coconut Grove\'s Bayshore Drive. The 20-story, 70-residence tower by Revuelta Architecture with interiors by Michele Bönan is anchored by an elaborate spa and wellness floor, including a five-room Roman bath circuit. Over 50% pre-sold.',
    views: 'Biscayne Bay panoramic views, Miami skyline',
    waterfront: true,
    shortTermRental: false,
    constructionStatus: 'Under construction / active preconstruction sales — 50%+ pre-sold',
    badge: 'TOP PICK',
    photos: [
      'https://www.miamicondoinvestments.com/wp-content/uploads/2024/05/four-seasons-residences-coconut-grove-5.jpg',
      'https://www.miamicondoinvestments.com/wp-content/uploads/2024/05/Four-Seasons-Residences-Coconut-Grove-Condos-2.jpg',
      'https://www.miamicondoinvestments.com/wp-content/uploads/2024/05/four-seasons-residences-coconut-grove-4.jpg',
      'https://www.miamicondoinvestments.com/wp-content/uploads/2024/05/four-seasons-residences-coconut-grove-10.jpg',
    ],
  },
  {
    id: 'the-well-coconut-grove',
    name: 'The Well Coconut Grove',
    address: '2855 Tigertail Avenue',
    area: 'Coconut Grove',
    city: 'Miami',
    tagline: '',
    developer: 'Terra',
    architecture: 'Arquitectonica',
    interiors: 'Meyer Davis',
    stories: 8,
    totalUnits: 194,
    bedrooms: [1, 2, 3, 4],
    sqftMin: 960,
    sqftMax: 4200,
    pricingFrom: 'From the $700s',
    priceFrom: 700000,
    pricePerSqft: null,
    deliveryYear: 2028,
    deliveryLabel: 'Q1 2028',
    deposit: '',
    amenities: [
      '13,000 sq ft wellness club with fitness center, spa, hyperbaric chamber, crystal lounges',
      '40,000 sq ft rooftop with pools, hot/cold plunges, pickleball court, fitness forest, restaurant',
      'Resident concierge & private dining room',
      'Children\'s room, yoga studio',
      'On-site physicians, lifestyle coaches, nutritionists, personal trainers',
    ],
    parkingSpaces: '',
    description: 'Terra\'s second wellness-branded tower on Tigertail Avenue with a full clinical wellness team on staff and a 40,000-square-foot rooftop wellness deck. Designed by Arquitectonica with interiors by Meyer Davis, the 8-story, 194-residence building spans 94 unique floor plans from one to four bedrooms.',
    views: 'Coconut Grove canopy and skyline views',
    waterfront: false,
    shortTermRental: false,
    constructionStatus: 'Preconstruction — broke ground February 2026',
    badge: '',
    photos: [
      'https://thewellcoconutgrovecondos.com/images/Rendering-of-THE-WELL-Coconut-Grove-Aerial-View-of-Rooftop.jpg',
      'https://thewellcoconutgrovecondos.com/images/Rendering-of-THE-WELL-Coconut-Grove-Exterior-Tigertail.jpg',
      'https://thewellcoconutgrovecondos.com/images/Rendering-of-THE-WELL-Coconut-Grove-Lobby-Reception.jpg',
      'https://thewellcoconutgrovecondos.com/images/Rendering-of-THE-WELL-Coconut-Grove-Rooftop-Pickleball-Court.jpg',
    ],
  },
  {
    id: 'ziggurat-coconut-grove',
    name: 'Ziggurat Coconut Grove',
    address: '3101 Grand Avenue',
    area: 'Coconut Grove',
    city: 'Miami',
    tagline: '',
    developer: 'Allen Morris Company',
    architecture: 'Oppenheim Architecture',
    interiors: 'Collarte Interiors',
    stories: 3,
    totalUnits: 19,
    bedrooms: [2, 3, 4, 5],
    sqftMin: null,
    sqftMax: null,
    pricingFrom: 'From $2.5 million',
    priceFrom: 2500000,
    pricePerSqft: null,
    deliveryYear: 2027,
    deliveryLabel: 'Q4 2027',
    deposit: '',
    amenities: [
      'Rooftop restaurant membership led by a Michelin-star chef',
      'Resort pool with hydrotherapy circuit',
      'Chef\'s grilling station & private cabanas',
      'Open-air paseo with dining and retail',
      'Wellness concept spaces',
      'Private event spaces',
    ],
    parkingSpaces: '',
    description: 'A boutique, eco-conscious mixed-use project by Oppenheim Architecture, Ziggurat pairs a trophy office building with just 19 ultra-luxury residences (two to five bedrooms) wrapped in nature-forward, terraced architecture. Residents get exclusive access to a Michelin-chef-led rooftop restaurant.',
    views: 'Coconut Grove views',
    waterfront: false,
    shortTermRental: false,
    constructionStatus: 'Under construction — sales gallery open, active pre-sales',
    badge: '',
    photos: [
      'https://d15zjc2r4e8kr7.cloudfront.net/9823/Floor%20Plans/ZIGGURAT/images/Oppenheim_GrandAveMiami_MoonstruckMild_www.mir.no-min.jpg',
      'https://d15zjc2r4e8kr7.cloudfront.net/9823/Floor%20Plans/ZIGGURAT/images/Ziggurat%20-%20Hero%20Shot%20-%20Corner%20Grand%20Ave%20and%20Matilda-min.jpg',
      'https://d15zjc2r4e8kr7.cloudfront.net/9823/Floor%20Plans/ZIGGURAT/images/Ziggurat-Hummingbird-01-min.jpg',
    ],
  },
  {
    id: 'the-avenue-coral-gables',
    name: 'The Avenue Coral Gables',
    address: '351 San Lorenzo Avenue',
    area: 'Coral Gables',
    city: 'Coral Gables',
    tagline: '',
    developer: 'Roger Development Group',
    architecture: 'Bermello Ajamil & Partners',
    interiors: 'Adriana Hoyos Design Studio',
    stories: 12,
    totalUnits: 54,
    bedrooms: [1, 2],
    sqftMin: 571,
    sqftMax: 978,
    pricingFrom: '',
    priceFrom: null,
    pricePerSqft: null,
    deliveryYear: 2026,
    deliveryLabel: '2026',
    deposit: '',
    amenities: [
      '24-hour reception, valet, concierge, security',
      'Resort-style pool deck (Level 9)',
      'Fiber-optic Wi-Fi',
      'Hammock garden',
      'Summer kitchens',
      'Fully furnished turnkey units',
    ],
    parkingSpaces: '',
    description: 'The Avenue is a 12-story, 54-residence hotel-condo hybrid and Coral Gables\' first tower approved for short-term rentals, giving owners hotel-style flexibility in the heart of the Gables. Compact one- and two-bedroom layouts come fully furnished with European kitchens by Adriana Hoyos and Sub-Zero/Wolf appliances.',
    views: '360-degree views of Coral Gables',
    waterfront: false,
    shortTermRental: true,
    constructionStatus: 'Under construction',
    badge: '',
    photos: [
      'https://www.miamicondoinvestments.com/wp-content/uploads/2023/08/the-avenue-condos-coral-gables-1.jpg',
      'https://www.miamicondoinvestments.com/wp-content/uploads/2023/08/the-avenue-condos-coral-gables-4.jpg',
      'https://www.miamicondoinvestments.com/wp-content/uploads/2023/08/the-avenue-condos-coral-gables-6.jpg',
    ],
  },
  {
    id: 'andare-residences-by-pininfarina',
    name: 'Andare Residences by Pininfarina',
    address: '788 E Las Olas Boulevard',
    area: 'Fort Lauderdale',
    city: 'Fort Lauderdale',
    tagline: '',
    developer: 'Related Group',
    architecture: 'Pininfarina',
    interiors: '',
    stories: 46,
    totalUnits: 163,
    bedrooms: [2, 3, 4],
    sqftMin: 1812,
    sqftMax: 4320,
    pricingFrom: 'From $2 million to $16 million',
    priceFrom: 2000000,
    pricePerSqft: null,
    deliveryYear: 2027,
    deliveryLabel: '2027',
    deposit: '',
    amenities: [
      'Rooftop pool',
      'Holistic wellness spa',
      'Advanced fitness studio',
      'Club lounge',
      'Full white-glove service suite',
    ],
    parkingSpaces: '',
    description: 'Related Group\'s $350 million Andare Residences is a 46-story tower designed with Italian design house Pininfarina, bringing automotive-inspired sculptural form to Las Olas Boulevard. Two- to four-bedroom residences feature floor-to-ceiling glass, private terraces, and imported Italian cabinetry. Over 50% pre-sold.',
    views: 'City skyline, Intracoastal, New River, and ocean views',
    waterfront: true,
    shortTermRental: false,
    constructionStatus: 'Under construction — 50%+ pre-sold',
    badge: '',
    photos: [
      'https://andareresidences.com/wp-content/uploads/2023/10/Andare-03-Hero_Night-02.jpg',
      'https://andareresidences.com/wp-content/uploads/2023/10/Andare-03-Club_Lounge_cam01-01.jpg',
      'https://andareresidences.com/wp-content/uploads/2023/10/ANDARE_ASLxRELATED_0738.jpg',
    ],
  },
  {
    id: 'the-ritz-carlton-residences-fort-lauderdale-beach',
    name: 'The Ritz-Carlton Residences, Fort Lauderdale Beach',
    address: '551 Bayshore Drive',
    area: 'Fort Lauderdale',
    city: 'Fort Lauderdale',
    tagline: '',
    developer: 'MICL Group & Admire Capital',
    architecture: 'Garcia Stromberg',
    interiors: 'Dan Fink Studio',
    stories: 13,
    totalUnits: 83,
    bedrooms: [2, 3],
    sqftMin: 1550,
    sqftMax: 3480,
    pricingFrom: 'From $2.5 million',
    priceFrom: 2500000,
    pricePerSqft: null,
    deliveryYear: 2029,
    deliveryLabel: '2029 (est.)',
    deposit: '',
    amenities: [
      'Lap pool & leisure pool',
      'Private cabanas',
      'Resident lounge',
      'Screening room',
      'Dock slips along the Intracoastal Waterway',
      'Full Ritz-Carlton branded service',
    ],
    parkingSpaces: '',
    description: 'A 13-story dual-tower development positioned directly between the Atlantic Ocean and the Intracoastal Waterway, offering just 83 residences with wide-plank white oak flooring and floor-to-ceiling sliding glass. Six penthouses include private rooftop terraces and plunge pools.',
    views: 'Atlantic Ocean and Intracoastal views',
    waterfront: true,
    shortTermRental: false,
    constructionStatus: 'Preconstruction — newly announced, interior renderings released 2026',
    badge: '',
    photos: [
      'https://images.prismic.io/theritzcarltonresidences-fortlauderdale/aPvC3LpReVYa3qFc_251024-MobileHero.jpg',
    ],
  },
  {
    id: 'st-regis-resort-residences-bahia-mar-fort-lauderdale',
    name: 'St. Regis Resort & Residences, Bahia Mar Fort Lauderdale',
    address: '801 Seabreeze Boulevard',
    area: 'Fort Lauderdale',
    city: 'Fort Lauderdale',
    tagline: '',
    developer: 'Related Group, Tate Capital, Rok Enterprises',
    architecture: 'Arquitectonica',
    interiors: '',
    stories: 23,
    totalUnits: 160,
    bedrooms: [1, 2, 3, 4],
    sqftMin: 1160,
    sqftMax: 3550,
    pricingFrom: 'Resort Collection from $2M; Residences Collection from $4.4M',
    priceFrom: 2000000,
    pricePerSqft: null,
    deliveryYear: null,
    deliveryLabel: 'Groundbreaking expected late 2026/early 2027',
    deposit: '1BR $150,000 / 2BR $200,000 / 3BR $250,000 / 4BR $300,000 (reservation-tier deposits)',
    amenities: [
      '250-slip yacht marina accommodating megayachts up to 350 ft',
      '37,000 sq ft of exclusive residential amenities',
      'Access to 65,000 sq ft of upscale retail, dining and entertainment',
      'Full St. Regis butler service',
    ],
    parkingSpaces: '',
    description: 'A $1 billion, nearly 40-acre transformation of the historic Bahia Mar marina, with two 23-story residential towers alongside a 24-story resort tower and a 30-story hotel. Three- and four-bedroom homes feature private elevator foyers and wraparound terraces overlooking the Atlantic, Intracoastal, and Fort Lauderdale skyline.',
    views: 'Atlantic Ocean, Intracoastal Waterway, and Fort Lauderdale skyline',
    waterfront: true,
    shortTermRental: false,
    constructionStatus: 'Preconstruction — pre-development, groundbreaking not yet underway',
    badge: '',
    photos: [
      'https://static.wixstatic.com/media/74d7a7_d9ec2db88fc844bfac409469b34470a3~mv2.png',
      'https://static.wixstatic.com/media/74d7a7_ff3c679524854ec4963494f442c10957~mv2.jpg',
      'https://static.wixstatic.com/media/74d7a7_7e903a9abea94a0eb3f956163a40e598~mv2.jpg',
    ],
  },
  {
    id: 'the-ritz-carlton-residences-pompano-beach',
    name: 'The Ritz-Carlton Residences, Pompano Beach',
    address: '1380 S Ocean Boulevard',
    area: 'Pompano Beach',
    city: 'Pompano Beach',
    tagline: '',
    developer: 'Fortune International Development, Oak Capital, Fairwinds',
    architecture: 'Luis Revuelta',
    interiors: '',
    stories: 32,
    totalUnits: 205,
    bedrooms: [1, 2, 3, 4, 5],
    sqftMin: 906,
    sqftMax: 7193,
    pricingFrom: 'From $7,233,000+ (remaining Beachfront Tower inventory)',
    priceFrom: 7233000,
    pricePerSqft: 1901,
    deliveryYear: 2026,
    deliveryLabel: '2026',
    deposit: '',
    amenities: [
      'Two infinity pools overlooking the ocean',
      'Private marina with 13 boat slips',
      'Yacht club',
      'Beach club',
      'Wellness center with spa',
      'Multiple fitness centers',
      'Restaurants and wine bar',
      'Virtual golf simulator',
      'Dog parks',
    ],
    parkingSpaces: 'Covered garage, valet, and guest parking',
    description: 'A two-tower ultra-luxury compound spanning 4.6 acres with both oceanfront and Intracoastal frontage — a 32-story Beachfront Tower and a 14-story Marina Tower (now 100% sold). Designed by Luis Revuelta. More than 92% sold overall, with only a handful of ocean-view 4-bedroom Beachfront Tower residences remaining.',
    views: 'Ocean, city, and Intracoastal views',
    waterfront: true,
    shortTermRental: false,
    constructionStatus: 'Under construction, nearing completion — 92%+ sold, very limited remaining inventory',
    badge: '',
    photos: [
      'https://imgprd.condoblackbook.com/buildings/2105/images/100193860_medium.webp',
      'https://imgprd.condoblackbook.com/buildings/2105/images/100193863_medium.webp',
      'https://imgprd.condoblackbook.com/buildings/2105/images/100193869_medium.webp',
    ],
  },
  {
    id: 'icon-beach-waterfront-residences',
    name: 'Icon Beach Waterfront Residences',
    address: '3724 South Ocean Drive',
    area: 'Hollywood',
    city: 'Hollywood',
    tagline: '',
    developer: 'Related Group & BH Group',
    architecture: 'CFE Architects',
    interiors: 'Meyer Davis',
    stories: 38,
    totalUnits: 350,
    bedrooms: [1, 2, 3],
    sqftMin: 948,
    sqftMax: 2580,
    pricingFrom: 'From $825,000 to $2.8 million',
    priceFrom: 825000,
    pricePerSqft: null,
    deliveryYear: 2028,
    deliveryLabel: '2028',
    deposit: '20% at Contract, 20% at Groundbreaking, 10% at Top-Off, 50% at Closing',
    amenities: [
      'Private marina',
      'Beach club',
      'Health club and spa',
      '40,000+ sq ft of outdoor amenities',
      'Expansive pool deck',
    ],
    parkingSpaces: '',
    description: 'Related Group and BH Group\'s Icon Beach Waterfront Residences is a 38-story, 350-unit tower overlooking the Intracoastal Waterway in Hollywood, designed by CFE Architects with interiors by Meyer Davis. One- to three-bedroom residences priced well below comparable Miami Beach or Fort Lauderdale beach product.',
    views: 'Atlantic Ocean and Intracoastal Waterway views',
    waterfront: true,
    shortTermRental: false,
    constructionStatus: 'Groundbreaking underway 2026 — active pre-sales',
    badge: 'BEST INVESTMENT',
    photos: [
      'https://iconhollywoodbeach.com/storage/icon-beach.png',
      'https://iconhollywoodbeach.com/storage/Related-Diplomat-02-Aerial_Looking_Downtown-02.jpg',
      'https://iconhollywoodbeach.com/storage/Related-Diplomat-02-PoolDeck_Cinema-01.jpg',
    ],
  },
  {
    id: 'the-residences-at-1428-brickell',
    name: 'The Residences at 1428 Brickell',
    address: '1428 Brickell Avenue',
    area: 'Brickell',
    city: 'Miami',
    tagline: '',
    developer: 'Ytech',
    architecture: 'ACPV (Antonio Citterio Patricia Viel) & Arquitectonica',
    interiors: '',
    stories: 70,
    totalUnits: 189,
    bedrooms: [2, 3, 4],
    sqftMin: 1800,
    sqftMax: 10000,
    pricingFrom: '2BR from $2.9M',
    priceFrom: 2900000,
    pricePerSqft: 1600,
    deliveryYear: 2029,
    deliveryLabel: '2029',
    deposit: '20% contract, 10% at 3mo, 10% top-off, 60% closing',
    amenities: [
      'World\'s first partially solar-powered high-rise (20K sq ft photovoltaic glass)',
      'Column-free 40-ft spans, 11+ ft ceilings, Gaggenau appliances',
      'Arclinea cabinetry, Italian marble, Rimadesio glass enclosures',
      '80,000 sq ft amenities for 189 units — rooftop observatory floor 70',
      '25% of building features two-story residences',
    ],
    parkingSpaces: '',
    description: 'The Residences at 1428 Brickell is an ultra-exclusive bayfront tower by Ytech — just 189 residences across 70 stories, designed by ACPV and Arquitectonica. As the world\'s first partially solar-powered high-rise, it pairs column-free 40-ft spans and 11+ ft ceilings with 80,000 sq ft of amenities and a rooftop observatory on floor 70.',
    views: 'East over Biscayne Bay, Brickell Key & Atlantic Ocean from higher floors',
    waterfront: true,
    shortTermRental: false,
    constructionStatus: 'Under construction',
    badge: 'MOST EXCLUSIVE',
    photos: [],
  },
  {
    id: 'okan-tower',
    name: 'Okan Tower',
    address: '555 North Miami Avenue',
    area: 'Downtown Miami',
    city: 'Miami',
    tagline: '',
    developer: 'Okan Group',
    architecture: 'Behar Font Architects',
    interiors: '',
    stories: 70,
    totalUnits: 163,
    bedrooms: [1, 2, 3],
    sqftMin: 698,
    sqftMax: 2071,
    pricingFrom: 'Sky residences from $522K | 3BR up to $2.8M | Penthouses from $1.9M',
    priceFrom: 522000,
    pricePerSqft: 1000,
    deliveryYear: 2027,
    deliveryLabel: 'Late 2027',
    deposit: '',
    amenities: [
      'Tulip-inspired curved glass facade (Turkish design)',
      'Fully integrated Hilton hotel services',
      'Italian cabinetry, Sub-Zero/Wolf appliances, 10+ ft ceilings',
      'Sky pool on 70th floor — among highest in North America',
      'Rooftop restaurant 67th floor, Hammam spa, wine cellar, cigar room',
    ],
    parkingSpaces: '',
    description: 'Okan Tower is a 70-story Downtown Miami landmark by Okan Group, wrapped in a tulip-inspired curved-glass facade and served by a fully integrated Hilton hotel program. Sky residences start from the $500Ks, with a 70th-floor sky pool, rooftop restaurant, Hammam spa, and unobstructed Biscayne Bay views from the 51st floor up.',
    views: 'Unobstructed Biscayne Bay & city skyline from floor 51+',
    waterfront: true,
    shortTermRental: true,
    constructionStatus: 'Foundation complete, vertical construction underway',
    badge: 'BEST VALUE',
    photos: [],
  },
  {
    id: 'lofty-brickell',
    name: 'Lofty Brickell',
    address: 'One Brickell Riverfront',
    area: 'Brickell',
    city: 'Miami',
    tagline: '',
    developer: 'Newgard Development Group',
    architecture: 'Arquitectonica',
    interiors: 'INC | PH by Artefacto',
    stories: 44,
    totalUnits: 364,
    bedrooms: [0, 1, 2],
    sqftMin: 535,
    sqftMax: 1410,
    pricingFrom: 'From $600K to $3.5M',
    priceFrom: 600000,
    pricePerSqft: 1100,
    deliveryYear: 2027,
    deliveryLabel: 'November 2027',
    deposit: '',
    amenities: [
      'Short-term rental friendly — DAILY rentals allowed',
      'Part of One Brickell Riverfront with The Standard Residences',
      'Fully finished & furnished at delivery (curated by INC)',
      'Marina access, connected to The Underline linear park',
      'Penthouse collection furnished by Artefacto (Brazilian luxury)',
    ],
    parkingSpaces: '',
    description: 'Lofty Brickell is a 44-story riverfront tower by Newgard Development on One Brickell Riverfront, delivered fully finished and furnished with DAILY short-term-rental capability. Marina access, Miami River views, and a penthouse collection by Artefacto make it a standout investment play from the $600Ks.',
    views: 'Miami River views, city skyline',
    waterfront: true,
    shortTermRental: true,
    constructionStatus: 'Currently at 20th floor',
    badge: 'BEST INVESTMENT',
    photos: [],
  },
];

// Distinct areas for filter dropdowns (derived).
export const PRECON_AREAS = [...new Set(PRECONSTRUCTIONS.map(p => p.area))].sort();
export const PRECON_DEVELOPERS = [...new Set(PRECONSTRUCTIONS.map(p => p.developer))].sort();
